### ISSUE TITLE
__apiDocuGenerate stop working even on older code base when it was working

### ISSUE THREAD

**Issue by ItsEmilyJpg** [contributte/api-docu#10]
ApiDocu not detecting parameter in URL for start generating docs, even on 2-3 old code base when it was working it stops working.

I think it must be something changed in Nette because it can update on minor versions.

**Comment by paveljanda** [comment]
Do you have any idea what change in Nette could that be?

**Comment by ItsEmilyJpg** [comment]
So, it was not that case, but there is very ugly side effect, when switch order registrations of ApiDocu and ApiRouter. Yep it is in docs, but its very hidden.

So problem solved :) Maybe do some ApiRouter registration detection and throw exception.

**Comment by paveljanda** [comment]
Ok, I am glad it is solved
