### ISSUE TITLE
How to hide not-meaningful APIs

### ISSUE THREAD

**Issue by repli2dev** [contributte/api-docu#5]
I wanted to create REST API in one project with requirement that it only have GET method (is for read only)... However documentation via ApiDocu still puts the documentation from persenter to the documentation:

![snimek obrazovky 2017-02-26 v 9 13 47](https://cloud.githubusercontent.com/assets/475549/23338186/2b895846-fc04-11e6-9c30-ca708da889f3.png)

How can I get rid of it (the second row)?

**Comment by paveljanda** [comment]
@repli2dev Can you show me your presenter code?

**Comment by repli2dev** [comment]
Yes, here: https://github.com/datoszs/czech-lawyers/blob/develop/app/API/Presenters/AdvocateAutocompletePresenter.php

**Comment by paveljanda** [comment]
@repli2dev Try adding:
```
methods={
    "GET"="run"
},
```

to the presenter annotation. Did it help?

**Comment by repli2dev** [comment]
It didn't help, the generated API doc looks still the same.

**Comment by paveljanda** [comment]
@repli2dev Aaaah, sorry. Fixed in `1.2.10`

**Comment by repli2dev** [comment]
Installed ublaboo-router 1.2.10, regenerated API doc, but nothing has changed.

**Comment by paveljanda** [comment]
@repli2dev Have you flushed the cache?

**Comment by repli2dev** [comment]
Yes :/
